import type { Theme } from './types.js';

export const lightTheme = Object.freeze({
  colorScheme: 'light',
  colorNeutralForeground1: '#172b3a',
  colorNeutralForeground2: '#3c5668',
  colorBrandForeground1: '#28536a',
  colorNeutralBackground1: '#ffffff',
  colorNeutralBackground2: '#f3f6f8',
  colorNeutralBackground1Hover: '#edf5f8',
  colorNeutralStroke1: '#c8d5de',
  colorNeutralStroke2: '#dbe4eb',
  colorNeutralStroke3: '#d9e3ea',
  colorNeutralStrokeAccessible: '#7b8995',
  colorBrandStroke1: '#176d91',
  fontFamilyBase: 'system-ui, sans-serif',
  fontSizeBase100: '0.8rem',
  fontSizeBase200: '0.9rem',
  fontSizeBase300: '1rem',
  fontSizeBase400: '1.2rem',
  fontWeightSemibold: '600',
  fontWeightBold: '700',
  lineHeightBase300: '1.5',
  borderRadiusSmall: '0.4rem',
  borderRadiusMedium: '0.5rem',
  borderRadiusLarge: '0.8rem',
  strokeWidthThin: '1px',
  strokeWidthThick: '3px',
  spacingHorizontalXS: '0.65rem',
  spacingHorizontalS: '0.8rem',
  spacingHorizontalM: '1rem',
  spacingHorizontalL: '1.5rem',
  spacingVerticalXS: '0.4rem',
  spacingVerticalS: '0.5rem',
  spacingVerticalM: '0.75rem',
  spacingVerticalL: '1rem',
  spacingVerticalXL: '1.5rem',
  spacingVerticalXXL: '2rem',
  spacingVerticalXXXL: '3rem',
});

export const darkTheme: Theme = Object.freeze({
  ...lightTheme,
  colorScheme: 'dark',
  colorNeutralForeground1: '#e8f0f5',
  colorNeutralForeground2: '#b3c7d4',
  colorBrandForeground1: '#9bcde5',
  colorNeutralBackground1: '#15232e',
  colorNeutralBackground2: '#0d1720',
  colorNeutralBackground1Hover: '#203a49',
  colorNeutralStroke1: '#415868',
  colorNeutralStroke2: '#304553',
  colorNeutralStroke3: '#415868',
  colorNeutralStrokeAccessible: '#7995a6',
  colorBrandStroke1: '#64b5da',
});
